import { Router } from "express";
import * as C from "../controllers/merchantAuth";
import { validate } from "../middlewares/validate";
import { authMiddleware } from "../middlewares/auth";
import { merchantRegisterSchema, loginSchema, verifyEmailSchema, forgotPasswordSchema, resetPasswordSchema, resendCodeSchema } from "../utils/validation";
const router = Router();
router.post("/register", validate(merchantRegisterSchema), C.register);
router.post("/verify-email", validate(verifyEmailSchema), C.verifyEmail);
router.post("/resend-code", validate(resendCodeSchema), C.resendCode);
router.get("/check-company/:name", C.checkCompanyName);
router.post("/login", validate(loginSchema), C.login);
router.post("/forgot-password", validate(forgotPasswordSchema), C.forgotPassword);
router.post("/reset-password", validate(resetPasswordSchema), C.resetPassword);
router.post("/refresh-token", C.refreshToken);
router.post("/logout", authMiddleware, C.logout);
router.get("/me", authMiddleware, C.getMe);
router.put("/profile", authMiddleware, C.updateProfile);
router.delete("/account", authMiddleware, C.deleteAccount);
router.put("/lang", authMiddleware, C.updateLang);
router.put("/update-images", authMiddleware, C.updateImages);
router.get("/delivery-wilayas", authMiddleware, C.getMyDeliveryWilayas);
router.put("/update-delivery-wilayas", authMiddleware, C.updateDeliveryWilayas);
export default router;
